[package]
name = "fips_203"
version = "0.1.0"
edition = "2021"

[lib]
name = "fips203"
[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
sha3 = {version="0.10.8", default-features=false}
rand_chacha = {version="0.9.0", default-features=false}
rand_core = "0.9.0"
getrandom = {version="0.3.1", optional=true}

[features]
default = ["std"]
std = ["rand_core/os_rng", "getrandom"]